#ifndef CSCREENPUBLIC
#define CSCREENPUBLIC

enum CScreenPositionType
{
    CSCREEN_POSITION_TYPE_NOT_CONTAIN,
    CSCREEN_POSITION_TYPE_CONTAIN,
    CSCREEN_POSITION_TYPE_TOP_LEFT,
    CSCREEN_POSITION_TYPE_TOP_MIDDLE,
    CSCREEN_POSITION_TYPE_TOP_RIGHT,
    CSCREEN_POSITION_TYPE_LEFT_MIDDLE,
    CSCREEN_POSITION_TYPE_RIGHT_MIDDLE,
    CSCREEN_POSITION_TYPE_BOTTOM_LEFT,
    CSCREEN_POSITION_TYPE_BOTTOM_MIDDLE,
    CSCREEN_POSITION_TYPE_BOTTOM_RIGHT
};

#endif // CSCREENPUBLIC

