#ifndef CSCREENPUBLIC
#define CSCREENPUBLIC

enum CScreenShotState
{
    CSCREEN_SHOT_STATE_INITIALIZED,
    CSCREEN_SHOT_STATE_LOCKED,
    CSCREEN_SHOT_STATE_SELECTED,
    CSCREEN_SHOT_STATE_EDITED,
    CSCREEN_SHOT_STATE_FINISHED
};

enum CScreenPositionType
{
    CSCREEN_POSITION_TYPE_NOT_CONTAIN,
    CSCREEN_POSITION_TYPE_CONTAIN,
    CSCREEN_POSITION_TYPE_TOP_LEFT,
    CSCREEN_POSITION_TYPE_TOP_MIDDLE,
    CSCREEN_POSITION_TYPE_TOP_RIGHT,
    CSCREEN_POSITION_TYPE_LEFT_MIDDLE,
    CSCREEN_POSITION_TYPE_RIGHT_MIDDLE,
    CSCREEN_POSITION_TYPE_BOTTOM_LEFT,
    CSCREEN_POSITION_TYPE_BOTTOM_MIDDLE,
    CSCREEN_POSITION_TYPE_BOTTOM_RIGHT
};

enum CScreenButtonType
{
    CSCREEN_BUTTON_TYPE_UNDEFINED,
    CSCREEN_BUTTON_TYPE_RECT,
    CSCREEN_BUTTON_TYPE_CANCLE,
    CSCREEN_BUTTON_TYPE_OK,
};

#endif // CSCREENPUBLIC

